# Generated by Django 5.0.6 on 2024-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_image/default_error.png', upload_to='blog_image/%Y/%m/%d/'),
        ),
    ]
